services:
  fastzero_database:
    image: postgres
    container_name: fastzero_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  fastzero_app:
    image: fast_zero
    build: .
    container_name: fastzero_app
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - fastzero_database
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@fastzero_database:5432/${POSTGRES_DB}

volumes:
  pgdata:
